<aside class="c-banner">
	
	<div class="l-wrap">

		<h1 class="h-banner">Start a family tradition today</h1>

		<p>Have you ever wondered how Santa knows who should be on the Naughty or Nice list?</p>

		<p class="c-banner__uselfs">Us Elves of course</p>

		<p>We watch you all the time to make sure you are being good and kind.</p>

		<a href="\elf-sets.html" class="btn btn--a">Buy yours today</a>

	</div>

</aside>