<blockquote class="quote">
		
	<p>“This is an absolutely brilliant idea, and this Elf is perfect for the job! I was a little surprised at how small it was to begin with but the size was actually perfect as were the Velcro hands too. You could put him in all sorts of situations, which would have been more difficult with a large Elf. The kids totally believed in him from day one. It made Christmas extra magical”</p>

	<footer>
		<cite>S Morgan</cite>
	</footer>

</blockquote>
